### ISSUE TITLE
More Than Puppies

### ISSUE THREAD

**Issue by cogdog** [troutcolor/puppies#1]
I'm in awe John, and in between first seeing it and looking again, you added the audio attribution.

Was wondering if you could make a tag entry field, so someone could switch it up to find gifs and sounds for other tags. Or, even more fun, if you could have different tags, so you could remix gifs of "business" with the sound of "pigs"

But the default should always be puppies. Wait until you see how appropriate this is today.

Of course, I could get off my lazy butt and fork it (eating my own puppy food)

**Comment by troutcolor** [comment]
Hi Alan, 
Certainly could search for sounds/gifs. 

I just recycled stuff from 
http://johnjohnston.neocities.org
Which can swap gifs and sounds searched for. 

Trying to re via email here. 

This git stuff comes alive when you can play with someone else. 

Typo Alert from my phone, fat fingers. 
http://johnjohnston.info

**Comment by troutcolor** [comment]
Added a search.
FWIW workflow:
Desktop created brach search, checked it out and worked on it. 
switched to master and merged search branch
Then followed these instructions to update ghpages from master.
https://gist.github.com/troutcolor/44148b0057152ef3671ecc6dc7bb714f
Which I forked so they are not mine.
